name: Deploy & Migrate to Production

on:
  push:
    branches:
      - main

jobs:
  wait-for-vercel-deploy:
    name: Wait for Vercel Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Wait for Vercel deploy to succeed
        run: |
          for i in {1..30}; do
            result=$(curl -s -H "Authorization: Bearer $VERCEL_TOKEN" \
              "https://api.vercel.com/v13/deployments?projectId=$VERCEL_PROJECT_ID" \
              | jq '.deployments[] | select(.state == "READY")')
            if [ -n "$result" ]; then
              echo "Deployment is READY."
              break
            fi
            echo "Waiting for deployment to be READY..."
            sleep 10
          done
          if [ -z "$result" ]; then
            echo "Timed out waiting for deployment to be READY."
            exit 1
          fi
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  migrate:
    name: Push Drizzle Schema to DB
    needs: wait-for-vercel-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Drizzle push
        run: pnpm drizzle-kit push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}